services:
  - type: web
    name: appdaf
    env: docker
    region: frankfurt
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: appdaf-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: appdaf-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: appdaf-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: appdaf-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: appdaf-db
          property: password
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: eu-west-1
      - key: AWS_BUCKET
        value: your-bucket-name
  - type: web
    name: appdaf-pgadmin
    env: docker
    region: frankfurt
    plan: starter
    buildCommand: docker build -t appdaf-pgadmin ./docker/pgadmin
    startCommand: docker run -p 8080:80 appdaf-pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: laye@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false  # For security, set this in Render dashboard
      - key: PGADMIN_CONFIG_SERVER_MODE
        value: "False"
    healthCheckPath: /

databases:
  - name: appdaf-db
    region: frankfurt
    plan: starter