FROM dpage/pgadmin4:latest

# Configuration supplémentaire si nécessaire
ENV PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
ENV PGADMIN_CONFIG_LOGIN_BANNER="Environnement de production"

USER pgadmin

# Le port par défaut est 80
EXPOSE 80